CREATE TABLE IF NOT EXISTS site (
	site_id INTEGER PRIMARY KEY,
	version REAL NOT NULL,
	first_run INTEGER NOT NULL DEFAULT 1,
  	storage TEXT,
	secret TEXT,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user (
	user_id INTEGER PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
  	password TEXT NOT NULL,
  	permission INTEGER NOT NULL DEFAULT 1,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file (
	file_id INTEGER PRIMARY KEY,
	filename TEXT NOT NULL,
	path TEXT,
	size INTEGER NOT NULL,
  	file_type TEXT,
  	owner_id INTEGER NOT NULL,
  	parent_id INTEGER NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	last_modified_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO site(version, created_at) VALUES(0.1, datetime());