CREATE TABLE IF NOT EXISTS site (
	id INTEGER PRIMARY KEY,
	firstRun INTEGER NOT NULL DEFAULT 1,
	port INTEGER NOT NULL DEFAULT 3000,
	allowGuest INTEGER NOT NULL DEFAULT 1,
    defaultUserGroup INTEGER NOT NULL DEFAULT 2,
	lang INTEGER NOT NULL DEFAULT 1,
	createAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);